site_name: SeaDoc Specification
site_author: seafile
docs_dir: ./docs
site_url: https://haiwen.github.io/seadoc-specification/seadoc/

repo_name: haiwen/seadoc-specification
repo_url: https://github.com/haiwen/seadoc-specification/
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2024 seafile

theme:
  name: material
  highlightjs: true
  hljs_languages:
    - yaml
    - bash
    - javascript
    - python
  # icon:
  logo: assets/seafile-logo.png
  favicon: assets/favicon.ico
  # features:
  # - tabs
  palette:
    primary: deep orange
    accent:

plugins:
  - search # necessary for search to work
  - awesome-pages

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/haiwen/seadoc-specification/

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
      toc_depth: "1-4"
  - pymdownx.superfences

# Page tree
nav:
  - Introduction: readme.md
  - Seadoc Support Types: support-types.md
  - Seadoc Data Structure:
      - Blockquote: data-structure/blockquote.md
      - Callout: data-structure/callout.md
      - Check_list_item: data-structure/check_list_item.md
      - Code_block: data-structure/code_block.md
      - File_link: data-structure/file_link.md
      - Header: data-structure/header.md
      - Image: data-structure/image.md
      - Link: data-structure/link.md
      - List: data-structure/list.md
      - Mention: data-structure/mention.md
      - Multi_column: data-structure/multi_column.md
      - Paragraph: data-structure/paragraph.md
      - Sdoc_link: data-structure/sdoc_link.md
      - Table: data-structure/table.md
